# Generated by Django 6.0.7 on 2026-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("AccountID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "AccountType",
                    models.CharField(
                        choices=[("Basic", "Basic"), ("Premium", "Premium")]
                    ),
                ),
                ("SortCode", models.CharField(max_length=8)),
                ("BalanceInGBP", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "CreditUsed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "CreditLimit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "AccruedReceivableInterestInGBP",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "AccruedPayableInterestInGBP",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
            ],
        ),
    ]
