# Generated by Django 6.0.7 on 2026-07-31 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="CustomerID",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
