# Generated by Django 6.0.7 on 2026-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "TransactionID",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("AccountID", models.BigIntegerField()),
                ("BankSortCode", models.CharField(max_length=8)),
                ("Amount", models.BigIntegerField()),
                (
                    "Outcome",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Complete", "Complete"),
                            ("Failed", "Failed"),
                        ]
                    ),
                ),
                ("RequestDate", models.DateField()),
                ("SettlementDate", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
