# Generated by Django 6.0.7 on 2026-07-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("TransactionID", models.AutoField(primary_key=True, serialize=False)),
                ("BankSortCode", models.CharField(max_length=8)),
                ("Amount", models.BigIntegerField()),
                (
                    "Outcome",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Complete", "Complete"),
                            ("Failed", "Failed"),
                        ]
                    ),
                ),
                ("RequestDate", models.DateField()),
                ("SettlementDate", models.DateField(blank=True, null=True)),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.accounts",
                    ),
                ),
            ],
        ),
    ]
