# Generated by Django 6.0.7 on 2026-07-31 08:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(blank=True, max_length=100, null=True)),
                ("MiddleName", models.CharField(blank=True, max_length=100, null=True)),
                ("LastName", models.CharField(blank=True, max_length=100, null=True)),
                ("NInumber", models.CharField(blank=True, max_length=8, null=True)),
                ("Birthday", models.DateField(blank=True, null=True)),
                (
                    "Nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "CountryOfResidence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Municipality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("StreetName", models.CharField(blank=True, max_length=255, null=True)),
                ("StreetNumber", models.IntegerField(blank=True, null=True)),
                ("Postcode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "AccountStatus",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "CurrentSubscription",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("JoiningDate", models.DateField(blank=True, null=True)),
                (
                    "EmploymentStatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Self-employed", "Self-employed"),
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Zero-hours", "Zero-hours"),
                            ("Student", "Student"),
                            ("Unemployed", "Unemployed"),
                            ("Retired", "Retired"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "IncomeBand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("£0-£10,000", "£0-£10,000"),
                            ("£10,001-£30,000", "£10,001-£30,000"),
                            ("£30,001-£50,000", "£30,001-£50,000"),
                            ("£50,001-£100,000", "£50,001-£100,000"),
                            ("£100,000+", "£100,000+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Agriculture", "Agriculture"),
                            ("Healthcare", "Healthcare"),
                            ("Apparel", "Apparel"),
                            ("Hospitality", "Hospitality"),
                            ("Banking", "Banking"),
                            ("Insurance", "Insurance"),
                            ("Biotechnology", "Biotechnology"),
                            ("Machinery", "Machinery"),
                            ("Chemicals", "Chemicals"),
                            ("Manufacturing", "Manufacturing"),
                            ("Communications", "Communications"),
                            ("Media", "Media"),
                            ("Construction", "Construction"),
                            ("Medical Device", "Medical Device"),
                            ("Consulting", "Consulting"),
                            ("Not For Profit", "Not For Profit"),
                            ("Education", "Education"),
                            ("Other", "Other"),
                            ("Electronics", "Electronics"),
                            ("Recreation", "Recreation"),
                            ("Energy", "Energy"),
                            ("Retail", "Retail"),
                            ("Engineering", "Engineering"),
                            ("Shipping", "Shipping"),
                            ("Entertainment", "Entertainment"),
                            ("Technology", "Technology"),
                            ("Environmental", "Environmental"),
                            ("Telecommunications", "Telecommunications"),
                            ("Finance", "Finance"),
                            ("Transportation", "Transportation"),
                            ("Food & Beverage", "Food & Beverage"),
                            ("Utilities", "Utilities"),
                            ("Government", "Government"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ExperianCreditRating", models.IntegerField(blank=True, null=True)),
                (
                    "RiskCategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
