# Generated by Django 6.0.7 on 2026-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="JoiningDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
