# Generated by Django 6.0.7 on 2026-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customers_joiningdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="ExperianCreditRating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="RiskCategory",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                max_length=10,
                null=True,
            ),
        ),
    ]
