# Generated by Django 6.0.7 on 2026-07-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                ("CardID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CardType",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")]
                    ),
                ),
                (
                    "BespokeCashbackRatePayable",
                    models.DecimalField(decimal_places=5, max_digits=6),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Inactive", "Inactive"),
                            ("Inactive", "Active"),
                            ("Frozen", "Frozen"),
                            ("Expired", "Expired"),
                        ]
                    ),
                ),
                ("ActivationDate", models.DateField(blank=True, null=True)),
                ("ExpirationDate", models.DateField(blank=True, null=True)),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.accounts",
                    ),
                ),
            ],
        ),
    ]
